export const REQUEST_BATCH_LIST = "REQUEST_BATCH_LIST"
export const RECEIVE_BATCH_LIST = "RECEIVE_BATCH_LIST"
export const RECEIVE_BATCH_LIST_ERROR = "RECEIVE_BATCH_LIST_ERROR"

export const REQUEST_BATCH_ITEM = "REQUEST_BATCH_ITEM"
export const RECEIVE_BATCH_ITEM = "RECEIVE_BATCH_ITEM"
export const RECEIVE_BATCH_ITEM_ERROR = "RECEIVE_BATCH_ITEM_ERROR"

export const PRODUCT_BATCH_UPLOAD_START = "PRODUCT_BATCH_UPLOAD_START"
export const PRODUCT_BATCH_UPLOAD_END = "PRODUCT_BATCH_UPLOAD_END"
